/* polyspace<MISRA-C3:1.1:Not a defect:Justified> Too many macro definitions code are generated by Configuration tools ,such as:Vector Geny. */
/*******************************************************************************
|  File Name: CanApp.c
|  Description: Implementation of the AUTOSAR CAN Interface
|-------------------------------------------------------------------------------
|  (c) This software is the proprietary of Wenzhou Changjiang AutoMobile (CAEA).
|     All rights are reserved by CAEA.
|-------------------------------------------------------------------------------
| Initials      Name                   Company
| --------      ---------------------  -----------------------------------------
|                                  CAEA
|-------------------------------------------------------------------------------
|               R E V I S I O N   H I S T O R Y
|-------------------------------------------------------------------------------
| Date          Version      Author    Description
| ------------  --------     -------   -----------------------------------------
  2019.05.18     V1.0         xyh                                               

|******************************************************************************/


/*******************************************************************************
|    Other Header File Inclusion
|******************************************************************************/
#include "v_cfg.h"
#include "CanApp.h"
#include "il_inc.h"
#include "CanNm.h"
//#include "STD_PowerMode.h"
#include "ccl_inc.h"
#include "Can_Trcv.h"
/*******************************************************************************
|    Macro Definition
|******************************************************************************/
#define CeCanApp_u_SleepNotAllowed    0U
#define CeCanApp_u_SleepAllowed       0x01U
#define NMStatus_NETON  1U
#define CanApp_WAKEUP_ACTIVE       (1u)
#define CanApp_WAKEUP_PASSIVE      (0u)
/*******************************************************************************
|    Enum Definition
|******************************************************************************/

/*******************************************************************************
|    Typedef Definition
|******************************************************************************/

/*******************************************************************************
|    Global variables Declaration
|******************************************************************************/

/*******************************************************************************
|    Static local variables Declaration
|******************************************************************************/
   
static uint8  SeCanApp_u_BusOffStaus;
static uint8  SeCanApp_BusOffOccurNum;
static uint8  SeCanApp_u_NetWorkStaus;
static uint8  SeCanApp_u_WakeupMode = 0U;/*0: passive wake up ,1: active wake up*/

static uint8  MessageRxReceiveIsOk[VeCanApp_e_MsgMaxNum];
static uint8  SeCanApp_u_MsgPresentSts[VeCanApp_e_MsgMaxNum];
static uint8  SeCanApp_u_MsgReceiveSts[VeCanApp_e_MsgMaxNum];

/*VIU_FR_1C3*/
static uint16 SeCanApp_u_EspVehSpd;
static uint8 SeCanApp_u_EspVehSpdVld;

/*VIU_FR_288*/
static uint8 SeCanApp_u_BcmPwrStsFb;

/*VIU_FR_2EC*/
static uint8 SeCanApp_u_VcuGearPosn;
static uint8 SeCanApp_u_VcuVehGearPosnVld;

/*VIU_FR_2EF*/
static uint32 SeCanApp_u_CdcTotMilg;

/*VIU_FR_2F7*/
static uint8 SeCanApp_u_TboxLocalTiDate;
static uint8 SeCanApp_u_TboxLocalTiHr;
static uint8 SeCanApp_u_TboxLocalTiMins;
static uint8 SeCanApp_u_TboxLocalTiMth;
static uint8 SeCanApp_u_TboxLocalTiSec;
static uint8 SeCanApp_u_TboxLocalTiVld;
static uint8 SeCanApp_u_TboxLocalTiYear;

/*VIU_FR_3D1*/
static uint8 SeCanApp_u_DcdcOperSts;

/*VIU_FR_3D3*/
static uint8 SeCanApp_u_BcuOperMod;

/*VIU_FR_3ED*/
static uint8 SeCanApp_u_FridgeUnlockCtrl;
static uint8 SeCanApp_u_FridgeDoorWarnTimeSet;
static uint8 SeCanApp_u_FridgeChdLockReq;
static uint8 SeCanApp_u_EgySaveModReq;
static uint8 SeCanApp_u_FridgeWorkReq;
static uint8 SeCanApp_u_FridgeQFunReq;
static uint8 SeCanApp_u_ContinueWorkSw;
static uint8 SeCanApp_u_ContinueWorkTimeSet;
static uint8 SeCanApp_u_FridgeUVLedReq;
static uint8 SeCanApp_u_FridgeUVLedWorkTimeSet;
static uint8 SeCanApp_u_FridgeModeReq;
static uint8 SeCanApp_u_FridgeCoolTempReq;
static uint8 SeCanApp_u_FridgeHeatTempReq;
static uint8 SeCanApp_u_VrhcuExOffReas;
static uint8 SeCanApp_u_VrhcuONReas;

static uint8  SeCanApp_u_ReqNetFlag;
static uint8  SeCanApp_u_DiagReqNetFlag;
static uint8  SeCanApp_u_EnableImmediateNmTx;
static uint8  SeCanApp_u_EnableRequestCommunication;
static uint8  SeCanApp_u_WakeUpSource_Nm;
static uint8  SeCanApp_u_AwakeSource_Nm;   
static uint16 SeCanApp_w_DiagReqNetCount;

/*******************************************************************************
|    static Local Functions Declaration
|******************************************************************************/
static void CanApp_SignalRecMainFunc(void);
static void CanApp_CheckPositiveWakeup(void);
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
void CanApp_SetPositiveReqNet(uint8 LeCanApp_u_ReqNetFlag)
{
    SeCanApp_u_ReqNetFlag = LeCanApp_u_ReqNetFlag;
}

/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
void CanApp_SetDiagReqNet(uint8 LeCanApp_u_DiagReqNetFlag)
{
    SeCanApp_u_DiagReqNetFlag = LeCanApp_u_DiagReqNetFlag;
}

/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
uint8 CanApp_GetDiagReqNet(void)
{
    return SeCanApp_u_DiagReqNetFlag;
}




/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
void CanApp_SetWakeupMode_NM(uint8 LeCanApp_u_WakeUpStateChange)
{
    SeCanApp_u_WakeupMode = (LeCanApp_u_WakeUpStateChange != 0U) ? CanApp_WAKEUP_ACTIVE : CanApp_WAKEUP_PASSIVE;
    /* inform lower layer (CanTrcv) about the wakeup mode to avoid reverse dependency */
    CanTrcv_SetWakeupMode(SeCanApp_u_WakeupMode);
}

/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
uint8 CanApp_HoldWakeupMode_Flag(void)
{
    return SeCanApp_u_WakeupMode;
}

/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
uint8 CanApp_GetWakeUpMode_Nm(void)
{
    return SeCanApp_u_WakeupMode;
}

/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
void CanApp_SetWakeUpSource_Nm(uint8 LeCanApp_u_WakeUpSource_Nm)
{
    SeCanApp_u_WakeUpSource_Nm = LeCanApp_u_WakeUpSource_Nm;
}
/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
void CanApp_SetAwakeSource_Nm(uint8 LeCanApp_u_AwakeSource_Nm)
{
    SeCanApp_u_AwakeSource_Nm = LeCanApp_u_AwakeSource_Nm;
}
/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
void CanApp_EnableImmediateNmTx(void)
{
    SeCanApp_u_EnableImmediateNmTx = 1u;
}
/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
void CanApp_DisableImmediateNmTx(void)
{
    SeCanApp_u_EnableImmediateNmTx = 0u;
}
/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
//Enable request communication.
void CanApp_EnableRequestCommunication(void)
{
    SeCanApp_u_EnableRequestCommunication = 1u;
}
/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
void CanApp_DisableRequestCommunication(void)
{
    SeCanApp_u_EnableRequestCommunication = 0u;
}
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
uint8 CanApp_GetPositiveReqNetFlag(void)
{
    return SeCanApp_u_ReqNetFlag;
}
/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
uint16 CanApp_GetDiagReqNetFlag(void)
{
    return SeCanApp_w_DiagReqNetCount;
}
/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
uint8 CanApp_GetImmediateNmTxFlag(void)
{
    return SeCanApp_u_EnableImmediateNmTx;
}
/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
uint8 CanApp_GetWakeUpSource_Nm(void)
{
    return SeCanApp_u_WakeUpSource_Nm;
}
/*******************************************************************************
Name      :
Syntax      :
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
uint8 CanApp_GetAwakeSource_Nm(void)
{
    return SeCanApp_u_AwakeSource_Nm;
}
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
static void CanApp_CheckPositiveWakeup(void)
{
    static uint8 SeCanApp_u_WakeupFlag = 0U;

     /* ========== Active Wake-up Mode ========== */
    if (SeCanApp_u_WakeupMode == 1U)
    {
        /*Request and maintain the network as long as communication is allowed (typically enabled after initialization). */
        if (0U != SeCanApp_u_EnableRequestCommunication)
        {
            if (SeCanApp_u_WakeupFlag != 0xAAU)
            {
                (void)CclRequestCommunication(0U);
                SeCanApp_u_WakeupFlag = 0xAAU;
            }
        }
        else
        {
            /* When communication is prohibited (which rarely occurs), the network is disconnected. */
            if (0xAAU == SeCanApp_u_WakeupFlag)
            {
                CclReleaseCommunication(0U);
                SeCanApp_u_WakeupFlag = 0U;
            }
        }
        /* In the active mode, completely ignore the subsequent diagnostic timer and other logic, and directly return. */
        return;
    }

     /* ========== Passive Wake-up Mode ========== */
    
    if(0x0U != SeCanApp_u_DiagReqNetFlag)/*Request network for 6s when receive diag ID*/
    {
        SeCanApp_u_DiagReqNetFlag = 0U;
        SeCanApp_w_DiagReqNetCount = 1000U; /*5s*/
    }
    if(0x0U != SeCanApp_w_DiagReqNetCount)
    {
        SeCanApp_w_DiagReqNetCount--;
    }
    
    if(((0U != SeCanApp_w_DiagReqNetCount) || (CanMsg_BcmPwrStsFb_OFF != SeCanApp_u_BcmPwrStsFb))
     && (0U != SeCanApp_u_EnableRequestCommunication))
    {
        if (CanNm_NmState[0] != NM_STATE_PREPARE_BUS_SLEEP)
        {
            (void)CclRequestCommunication(0U);
             SeCanApp_u_WakeupFlag = 0xAAU;
        }
    }
    else
    {
        if(0xAAU == SeCanApp_u_WakeupFlag)
        {
            CclReleaseCommunication(0U);
            SeCanApp_u_WakeupFlag = 0U;
        }
    }
} 
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
void CanApp_u_SetBusOffStaus(uint8 LeCanSignal_u_Idx)
{
    SeCanApp_u_BusOffStaus = LeCanSignal_u_Idx;
} 
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
uint8 CanApp_u_GetBusOffStaus(void)
{  
    return SeCanApp_u_BusOffStaus;
}
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
void CanApp_u_SetNetWorkStaus(uint8 LeCanSignal_u_Idx)
{  
    SeCanApp_u_NetWorkStaus = LeCanSignal_u_Idx;
}
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
uint8 CanApp_u_GetNetWorkStaus(void)
{
    return SeCanApp_u_NetWorkStaus;
}
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/ 
uint8 GetCanApp_u_NetWorkSleepAllowed(void)
{
    uint8 LeCanApp_u_NetWorkSleep =CeCanApp_u_SleepNotAllowed;

    if((0u == SeCanApp_u_NetWorkStaus)&&( CeCanTrcv_e_Standbymode == GetCanTrcv_CurrentMode()))
    {
        LeCanApp_u_NetWorkSleep = CeCanApp_u_SleepAllowed;
    }
    else
    {
        LeCanApp_u_NetWorkSleep = CeCanApp_u_SleepNotAllowed;
    }
    return LeCanApp_u_NetWorkSleep;
}

/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/
static void CanApp_SignalRecMainFunc(void)
{
    if(NMStatus_NETON == CanApp_u_GetNetWorkStaus()) 
    {
        /*VIU_FR_1C3*/
        if((uint8)1u == SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_1C3])
        {
            SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_1C3] = 0U;
            IlEnterCriticalEspVehSpd();
            SeCanApp_u_EspVehSpd = IlGetRxEspVehSpd();
            SeCanApp_u_EspVehSpdVld = IlGetRxEspVehSpdVld();
            IlLeaveCriticalEspVehSpd();
        }

        /*VIU_FR_288*/
        if((uint8)1u == SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_288])
        {
            SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_288] = 0U;
            IlEnterCriticalBcmPwrStsFb();
            SeCanApp_u_BcmPwrStsFb = IlGetRxBcmPwrStsFb();
            IlLeaveCriticalBcmPwrStsFb();
        }

        /*VIU_FR_2EC*/
        if((uint8)1u == SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_2EC])
        {
            SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_2EC] = 0U;
            IlEnterCriticalVcuGearPosn();
            SeCanApp_u_VcuGearPosn = IlGetRxVcuGearPosn();
            SeCanApp_u_VcuVehGearPosnVld = IlGetRxVcuVehGearPosnVld();
            IlLeaveCriticalVcuGearPosn();
        }
        /*VIU_FR_2EF*/
        if((uint8)1u == SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_2EF])
        {
            SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_2EF] = 0U;
            IlEnterCriticalCdcTotMilg();
            SeCanApp_u_CdcTotMilg = IlGetRxCdcTotMilg();
            IlLeaveCriticalCdcTotMilg();
        }

        /*VIU_FR_2F7*/
        if((uint8)1u == SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_2F7])
        {
            SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_2F7] = 0U;
            IlEnterCriticalTboxLocalTiDate();
            SeCanApp_u_TboxLocalTiDate = IlGetRxTboxLocalTiDate();
            SeCanApp_u_TboxLocalTiHr = IlGetRxTboxLocalTiHr();
            SeCanApp_u_TboxLocalTiMins = IlGetRxTboxLocalTiMins();
            SeCanApp_u_TboxLocalTiMth = IlGetRxTboxLocalTiMth();
            SeCanApp_u_TboxLocalTiSec = IlGetRxTboxLocalTiSec();
            SeCanApp_u_TboxLocalTiVld = IlGetRxTboxLocalTiVld();
            SeCanApp_u_TboxLocalTiYear = IlGetRxTboxLocalTiYear();
            IlLeaveCriticalTboxLocalTiDate();
        }

        /*VIU_FR_3D1*/
        if((uint8)1u == SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_3D1])
        {
            SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_3D1] = 0U;
            IlEnterCriticalDcdcOperSts();
            SeCanApp_u_DcdcOperSts = IlGetRxDcdcOperSts();
            IlLeaveCriticalDcdcOperSts();
        }

        /*VIU_FR_3D3*/
        if((uint8)1u == SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_3D3])
        {
            SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_3D3] = 0U;
            IlEnterCriticalBcuOperMod();
            SeCanApp_u_BcuOperMod = IlGetRxBcuOperMod();
            IlLeaveCriticalBcuOperMod();
        }

        /*VIU_FR_3ED*/
        if((uint8)1u == SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_3ED])
        {
            SeCanApp_u_MsgReceiveSts[VeCanApp_e_VIU_FR_3ED] = 0U;
            IlEnterCriticalFridgeUnlockCtrl();
            SeCanApp_u_FridgeUnlockCtrl = IlGetRxFridgeUnlockCtrl();
            SeCanApp_u_FridgeDoorWarnTimeSet = IlGetRxFridgeDoorWarnTimeSet();
            SeCanApp_u_FridgeChdLockReq = IlGetRxFridgeChdLockReq();
            SeCanApp_u_EgySaveModReq = IlGetRxEgySaveModReq();
            SeCanApp_u_FridgeWorkReq = IlGetRxFridgeWorkReq();
            SeCanApp_u_FridgeQFunReq = IlGetRxFridgeQFunReq();
            SeCanApp_u_ContinueWorkSw = IlGetRxContinueWorkSw();
            SeCanApp_u_ContinueWorkTimeSet = IlGetRxContinueWorkTimeSet();
            SeCanApp_u_FridgeUVLedReq = IlGetRxFridgeUVLedReq();
            SeCanApp_u_FridgeUVLedWorkTimeSet = IlGetRxFridgeUVLedWorkTimeSet();
            SeCanApp_u_FridgeModeReq = IlGetRxFridgeModeReq();
            SeCanApp_u_FridgeCoolTempReq = IlGetRxFridgeCoolTempReq();
            SeCanApp_u_FridgeHeatTempReq = IlGetRxFridgeHeatTempReq();
            SeCanApp_u_VrhcuExOffReas = IlGetRxVrhcuExOffReas();
            SeCanApp_u_VrhcuONReas = IlGetRxVrhcuONReas();
            IlLeaveCriticalFridgeUnlockCtrl();
        }

        if (0U == SeCanApp_u_MsgPresentSts[VeCanApp_e_VIU_FR_3ED])
        {
            SeCanApp_u_VrhcuExOffReas = 0U;
            SeCanApp_u_VrhcuONReas = 0U;
        }
        if (0U == SeCanApp_u_MsgPresentSts[VeCanApp_e_VIU_FR_288])
        {
            SeCanApp_u_BcmPwrStsFb = CanMsg_BcmPwrStsFb_OFF;
        }
        if (0U == SeCanApp_u_MsgPresentSts[VeCanApp_e_VIU_FR_1C3])
        {
            //SeCanApp_u_EspVehSpd = 0x1FFFU;
           // SeCanApp_u_EspVehSpdVld = 0x1U;
        }
        if (0U == SeCanApp_u_MsgPresentSts[VeCanApp_e_VIU_FR_2EC])
        {
           // SeCanApp_u_VcuVehGearPosnVld = 0x1U;
        }
        if (0U == SeCanApp_u_MsgPresentSts[VeCanApp_e_VIU_FR_2EF])
        {
            SeCanApp_u_CdcTotMilg = 0xFFFFFFU;
        }
        if (0U == SeCanApp_u_MsgPresentSts[VeCanApp_e_VIU_FR_2F7])
        {
            SeCanApp_u_TboxLocalTiVld = 0x1U;
        }
    }
    else
    {
        /*Keep value*/
    }
}
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/ 
void SetCanApp_BusOffOccurNumInc(void)
{
  SeCanApp_BusOffOccurNum++;

  if((uint8)5 <= SeCanApp_BusOffOccurNum)
  {
    SeCanApp_BusOffOccurNum = 5;
  }

}
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/ 
void SetCanApp_BusOffOccurNumClr(void)
{
  SeCanApp_BusOffOccurNum = 0u;
}

/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/ 
void SetCanApp_MsgReceiveSts( TeCanApp_e_MsgIdType LeCanApp_u_MsgIndex )
{ 
  SeCanApp_u_MsgReceiveSts[LeCanApp_u_MsgIndex] = 1u;
}
uint8 GetCanApp_MsgReceiveSts( TeCanApp_e_MsgIdType LeCanApp_u_MsgIndex )
{ 
    uint8 LeCanApp_u_Temp;
    LeCanApp_u_Temp = MessageRxReceiveIsOk[LeCanApp_u_MsgIndex];
    MessageRxReceiveIsOk[LeCanApp_u_MsgIndex] = 0u;
    return LeCanApp_u_Temp;
}
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/ 
void SetCanApp_MsgCurrentPresent( TeCanApp_e_MsgIdType LeCanApp_u_MsgIndex,uint8 LeCanApp_u_MsgSts)
{ 
  SeCanApp_u_MsgPresentSts[LeCanApp_u_MsgIndex] = LeCanApp_u_MsgSts;
}
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/ 
uint8 GetCanApp_u_MsgCurrentPresent( TeCanApp_e_MsgIdType LeCanApp_u_MsgIndex )
{
  return SeCanApp_u_MsgPresentSts[LeCanApp_u_MsgIndex];
}

/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/ 
 void CanApp_InitMemoryKAM(void)
 { 
     
 }  
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/ 
 void CanApp_InitMemory(void)
 {
    uint8 i;
    SeCanApp_u_NetWorkStaus = 1u;
    SeCanApp_u_BusOffStaus = 0u;
    SeCanApp_BusOffOccurNum =0u;

    /*VIU_FR_1C3*/
    SeCanApp_u_EspVehSpd = 0u;
    SeCanApp_u_EspVehSpdVld = 0u;

    /*VIU_FR_288*/
    SeCanApp_u_BcmPwrStsFb = CanMsg_BcmPwrStsFb_OFF;

    /*VIU_FR_2EC*/
    SeCanApp_u_VcuGearPosn =0u;
    SeCanApp_u_VcuVehGearPosnVld =0u;
    /*VIU_FR_2EF*/
    SeCanApp_u_CdcTotMilg =0u;
    /*VIU_FR_2F7*/
    SeCanApp_u_TboxLocalTiDate =0u;
    SeCanApp_u_TboxLocalTiHr =0u;
    SeCanApp_u_TboxLocalTiMins =0u;
    SeCanApp_u_TboxLocalTiMth =0u;
    SeCanApp_u_TboxLocalTiSec =0u;
    SeCanApp_u_TboxLocalTiVld =0u;
    SeCanApp_u_TboxLocalTiYear =0u;

    /*VIU_FR_3D1*/
    SeCanApp_u_DcdcOperSts = 2u;//0u;

    /*VIU_FR_3D3*/
    SeCanApp_u_BcuOperMod =0u;

    /*VIU_FR_3ED*/
    SeCanApp_u_FridgeUnlockCtrl =0u;
    SeCanApp_u_FridgeDoorWarnTimeSet =0u;
    SeCanApp_u_FridgeChdLockReq =0u;
    SeCanApp_u_EgySaveModReq =0u;
    SeCanApp_u_FridgeWorkReq =0u;
    SeCanApp_u_FridgeQFunReq =0u;
    SeCanApp_u_ContinueWorkSw =0u;
    SeCanApp_u_ContinueWorkTimeSet =0u;
    SeCanApp_u_FridgeUVLedReq =0u;
    SeCanApp_u_FridgeUVLedWorkTimeSet =0u;
    SeCanApp_u_FridgeModeReq =0u;
    SeCanApp_u_FridgeCoolTempReq =0u;
    SeCanApp_u_FridgeHeatTempReq =0u;
    SeCanApp_u_VrhcuExOffReas =0u;
    SeCanApp_u_VrhcuONReas =0u;

    for(i = 0u;i <(uint8)VeCanApp_e_MsgMaxNum;i++)
    {
        SeCanApp_u_MsgPresentSts[i] = 1U;
        SeCanApp_u_MsgReceiveSts[i] = 0U;
        MessageRxReceiveIsOk[i] = 0U;
    }
    
    SeCanApp_u_ReqNetFlag = 0U;
    SeCanApp_u_DiagReqNetFlag = 0U;
    SeCanApp_w_DiagReqNetCount = 0U;
    SeCanApp_u_EnableImmediateNmTx = 0U;
    SeCanApp_u_EnableRequestCommunication = 0U;
    SeCanApp_u_WakeUpSource_Nm = 0U;
    SeCanApp_u_AwakeSource_Nm = 0U;
 }
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/ 
void CanApp_MainFunction(void)
{     
  CanApp_SignalRecMainFunc();
  /*CanApp_SignalDebounceMainFunc();*/
  CanApp_CheckPositiveWakeup();
  CanCbk_GetBusOffDtcConditionState();
  
  if(AppDesc_28Service_Ctrl_Flag == FALSE)    //ggl  2025/12/11
  {
	  CanApp_SignalRecMainFunc();
  }
} 
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/ 
/*static void CanApp_u_MissMessageProcess(TeCanApp_e_MsgIdType LeCanApp_u_MsgIndex)
{
    if((uint8)1u == SeCanApp_u_MsgReceiveSts[LeCanApp_u_MsgIndex])
    {                 
        if(0U == MessageRxPresentCounter[LeCanApp_u_MsgIndex])
        {
            SeCanApp_u_MsgReceiveSts[LeCanApp_u_MsgIndex] = 0U;
            MessageRxPresentCounter[LeCanApp_u_MsgIndex] = MessagePeriodTimeTbl[LeCanApp_u_MsgIndex];
        }
        else
        {
            MessageRxPresentCounter[LeCanApp_u_MsgIndex] = 0U;
            SetCanApp_MsgCurrentPresent(LeCanApp_u_MsgIndex,1U);
        }
    }
}*/
/*******************************************************************************
Name      :
Syntax      : 
Sync/Async    : Synchronous
Reentrancy    :
Parameters(in)  : None
Parameters(out) : None
Return value  : None
Description    :
Call By      :
History
<No.>    <author>    <time>    <description>

|******************************************************************************/ 
uint8 CanCbk_GetBusOffDtcConditionState(void)/*BusOff DTC*/ //GGL
{  
	 uint8 LeCanApp_u_RetVal = 0u;
	if( 5U <= SeCanApp_BusOffOccurNum )
	{
		LeCanApp_u_RetVal = CeCanApp_e_True;
	}
	else
	{
		LeCanApp_u_RetVal = CeCanApp_e_False;
	}
	
	return LeCanApp_u_RetVal;
}

/*VIU_FR_1C3*/
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint16 GetCanApp_u_EspVehSpd(void)
{ 
    return SeCanApp_u_EspVehSpd;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_EspVehSpdVld(void)
{ 
    return SeCanApp_u_EspVehSpdVld;
}

/*VIU_FR_288*/
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_BcmPwrStsFb(void)
{ 
    return SeCanApp_u_BcmPwrStsFb;
}

/*VIU_FR_2EC*/
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_VcuGearPosn(void)
{ 
    return SeCanApp_u_VcuGearPosn;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_VcuVehGearPosnVld(void)
{ 
    return SeCanApp_u_VcuVehGearPosnVld;
}

/*VIU_FR_2EF*/
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint32 GetCanApp_u_CdcTotMilg(void)
{ 
    return SeCanApp_u_CdcTotMilg;
}
/*VIU_FR_2F7*/
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_TboxLocalTiDate(void)
{ 
    return SeCanApp_u_TboxLocalTiDate;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_TboxLocalTiHr(void)
{ 
    return SeCanApp_u_TboxLocalTiHr;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_TboxLocalTiMins(void)
{ 
    return SeCanApp_u_TboxLocalTiMins;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_TboxLocalTiMth(void)
{ 
    return SeCanApp_u_TboxLocalTiMth;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_TboxLocalTiSec(void)
{ 
    return SeCanApp_u_TboxLocalTiSec;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_TboxLocalTiVld(void)
{ 
    return SeCanApp_u_TboxLocalTiVld;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_TboxLocalTiYear(void)
{ 
    return SeCanApp_u_TboxLocalTiYear;
}

/*VIU_FR_3D1*/
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_DcdcOperSts(void)
{ 
    return SeCanApp_u_DcdcOperSts;
}

/*VIU_FR_3D3*/
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_BcuOperMod(void)
{ 
    return SeCanApp_u_BcuOperMod;
}
/*VIU_FR_3ED*/
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_FridgeUnlockCtrl(void)
{ 
    return SeCanApp_u_FridgeUnlockCtrl;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_FridgeDoorWarnTimeSet(void)
{ 
    return SeCanApp_u_FridgeDoorWarnTimeSet;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_FridgeChdLockReq(void)
{ 
    return SeCanApp_u_FridgeChdLockReq;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_EgySaveModReq(void)
{ 
    return SeCanApp_u_EgySaveModReq;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_FridgeWorkReq(void)
{ 
    return SeCanApp_u_FridgeWorkReq;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_FridgeQFunReq(void)
{ 
    return SeCanApp_u_FridgeQFunReq;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_ContinueWorkSw(void)
{ 
    return SeCanApp_u_ContinueWorkSw;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_ContinueWorkTimeSet(void)
{ 
    return SeCanApp_u_ContinueWorkTimeSet;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_FridgeUVLedReq(void)
{ 
    return SeCanApp_u_FridgeUVLedReq;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_FridgeUVLedWorkTimeSet(void)
{ 
    return SeCanApp_u_FridgeUVLedWorkTimeSet;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_FridgeModeReq(void)
{ 
    return SeCanApp_u_FridgeModeReq;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_FridgeCoolTempReq(void)
{ 
    return SeCanApp_u_FridgeCoolTempReq;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_FridgeHeatTempReq(void)
{ 
    return SeCanApp_u_FridgeHeatTempReq;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_VrhcuExOffReas(void)
{ 
    return SeCanApp_u_VrhcuExOffReas;
}
/*******************************************************************************
Name            :
Reentrancy        : None
Parameters(in)    : None
Parameters(out) : None
Return value    : None
Description        : -
Call By            :
|******************************************************************************/
uint8 GetCanApp_u_VrhcuONReas(void)
{ 
    return SeCanApp_u_VrhcuONReas;
}
/* polyspace:end<MISRA-C3:10.3,8.9,8.4,8.7,2.5,5.1,13.5:Not a defect:Justified> NO fluence */






void SetCanApp_ClearTimeOut(void)
{
    uint8 i;
    for(i = 0u;i <(uint8)VeCanApp_e_MsgMaxNum;i++)
    {
      //  SeCanApp_u_MsgPresentSts[i] = TRUE; 
        SeCanApp_u_MsgPresentSts[VeCanApp_e_VIU_FR_3ED] = TRUE;
        SeCanApp_u_MsgReceiveSts[i] = FALSE;
    }
}

