/* -----------------------------------------------------------------------------
  Filename:    appdesc.h
  Description: Interface towards the application used by CANdesc.
                
                Manufacturer: Vector
                EcuDocFile:   C:\Users\leisz70544\Desktop\K1LF01C_CFG_Canbedded\src\K1LF01C-E-CDD-A1.cdd
                Variant:      CommonDiagnostics

  Generated by CANdelaGen, Thu Sep 05 19:55:56 2019
 
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2013 by Vector Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vector Informatik 
  GmbH.
  
  Vector Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vector Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__APPDESC_H__)
#define __APPDESC_H__

/* -----------------------------------------------------------------------------
    &&&~ Configuration switches
 ----------------------------------------------------------------------------- */

#if !defined(__DESC_H__)
# error "Include sequence error! You must include desc.h before appDesc.h."
#endif



/* -----------------------------------------------------------------------------
    &&&~ Preprocessor constants (defines)
 ----------------------------------------------------------------------------- */

/* This magic number provides inter CANdesc generation process consistency check.All CANdesc files must have the same one. */
#define DESC_APPLICATION_INTERFACE_MAGIC_NUMBER                      21795

#define kApplDescFalse 0u
#define kApplDescTrue  1u
#define kApplDescNoOk  1u
#define kApplDescOk    0u
/* -----------------------------------------------------------------------------
    &&&~ Function prototypes
 ----------------------------------------------------------------------------- */
extern vuint8 AppDesc_28Service_Ctrl_Flag;
extern vuint8 AppDesc_28Service_CtrlNM_Flag;
extern vuint32 g_applDescSeedX;
#if defined (DESC_ENABLE_DEBUG_USER ) || defined (DESC_ENABLE_DEBUG_INTERNAL)
/* Assertion function for better integration support. */
void DESC_API_CALLBACK_TYPE ApplDescFatalError(vuint8 errorCode, vuint16 lineNumber);
#endif

#if defined (DESC_ENABLE_SPONTANEOUS_RES)
void DESC_API_CALLBACK_TYPE ApplDescSpontaneousResponseConfirmation(DESC_CONTEXT_FORMAL_PARAM_DEF_FIRST vuint8 status);
#endif

vuint8 DESC_API_CALL_TYPE ApplDescInitPosResFblBusInfo(t_descUsdtNetBus* pBusInfo);

/* If RCR-RP has been forced this confirmation function will notify the application about the transmission result. */
void DESC_API_CALLBACK_TYPE ApplDescRcrRpConfirmation(vuint8 status);
void DESC_API_CALLBACK_TYPE ApplDescOnTransitionSession(DescStateGroup newState, DescStateGroup formerState);
void DESC_API_CALLBACK_TYPE ApplDescOnTransitionSecurityAccess(DescStateGroup newState, DescStateGroup formerState);
void DESC_API_CALLBACK_TYPE ApplDescEcuResetHard(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescEcuResetSoft(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescClearDiagInfo(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDtcRNODTCBSM(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDtcRDTCBSM(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDtcRDTCSSBDTC(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDtcRSUPDTC(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWriteDidDID_0xF18C(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWriteDidDID_0xF1F0(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWriteDidDID_0xF1F6(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWriteDidDID_0xF1FA(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWriteDidDID_0xF1FC(DescMsgContext* pMsgContext);

void DESC_API_CALLBACK_TYPE ApplDescIoCtrlRetCtrlToEcuCPID_F1F1(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescIoCtrlShortTermAdjCPID_F1F1(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescIoCtrlRetCtrlToEcuCPID_F1F2(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescIoCtrlShortTermAdjCPID_F1F2(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescIoCtrlRetCtrlToEcuCPID_F1F3(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescIoCtrlShortTermAdjCPID_F1F3(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescIoCtrlRetCtrlToEcuCPID_F1F4(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescIoCtrlShortTermAdjCPID_F1F4(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescIoCtrlRetCtrlToEcuCPID_F1F5(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescIoCtrlShortTermAdjCPID_F1F5(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescControlDtcSettingEnable(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescControlDtcSettingDisable(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescPreWriteDidDID_0xF1F6(void);
void DESC_API_CALLBACK_TYPE ApplDescPreIoCtrlShortTermAdjCPID_F1F3(void);
void DESC_API_CALLBACK_TYPE ApplDescPreControlDtcSettingEnable(void);
void DESC_API_CALLBACK_TYPE ApplDescReadDidCPID_F1F1(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidCPID_F1F2(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidCPID_F1F3(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidCPID_F1F4(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidCPID_F1F5(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadMemoryByAddress(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWriteMemoryByAddress(DescMsgContext* pMsgContext);

void DESC_API_CALLBACK_TYPE ApplDescWriteDidDID_0xF089(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescWriteDidDID_0xF187(DescMsgContext* pMsgContext);

void DESC_API_CALLBACK_TYPE ApplDescPostEcuResetHard(vuint8 status);
void DESC_API_CALLBACK_TYPE ApplDescPostEcuResetSoft(vuint8 status);
/* Application condition checks */
void DESC_API_CALLBACK_TYPE ApplDescCheckCommCtrl(DESC_CONTEXT_FORMAL_PARAM_DEF_FIRST DescOemCommControlInfo *commControlInfo);

#if defined (DESC_ENABLE_COMM_CTRL_SUBNET_SUPPORT)
void DESC_API_CALLBACK_TYPE ApplDescSetCommMode(DescOemCommControlInfo *commControlInfo);
#endif

#if defined (DESC_ENABLE_RX_COMM_CONTROL)
void DESC_API_CALLBACK_TYPE ApplDescSetCommModeOnRxPath(DescOemCommControlInfo *commControlInfo);
#endif

/* Notification functions */
void DESC_API_CALLBACK_TYPE ApplDescOnCommunicationDisable(void);
void DESC_API_CALLBACK_TYPE ApplDescOnCommunicationEnable(void);

void DESC_API_CALLBACK_TYPE ApplDescCheckSessionTransition(DescStateGroup newState, DescStateGroup formerState);
/* application function which returns a randomly generated value each time it is called 
 * (e.g. current free running timer value)
 */
void ApplDescSecurityAccessGetSeed(DescSecurityAccessContext* pDescSecurityAccessContext);
/* application function which must evaluate the received key and confirm its validity.
 */
void ApplDescSecurityAccessCheckKey(DescSecurityAccessContext* pDescSecurityAccessContext);

#if defined (DESC_ENABLE_REPORT_ATT_CNTR_STATE)
/* application notification on time expiration */
void ApplDescSecurityAccessOnAttCntrChanged(DESC_CONTEXT_FORMAL_PARAM_DEF_FIRST DescSecAccAttCtrChgEvType chgEv, vuint8 newAttCounter);
#endif

void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF089(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF120(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF121(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF122(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF170(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF171(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF184(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF187(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF188(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF189(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF18A(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF18C(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF1F0(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF1F6(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF1F7(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF1F8(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF1F9(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF1FA(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF1FB(DescMsgContext* pMsgContext);
void DESC_API_CALLBACK_TYPE ApplDescReadDidDID_0xF1FC(DescMsgContext* pMsgContext);

#if defined (DESC_ENABLE_MULTI_CFG_SUPPORT)
/* Additionaly reject a supported PID (multi ECU configuration) */
DescBool ApplDescIsDataIdSupported(vuint16 pid);
#endif

void DESC_API_CALLBACK_TYPE ApplDescRtnCtrlStartRID_0203(DescMsgContext* pMsgContext);


#endif /* __APPDESC_H__ */
