/* polyspace<MISRA-C3:1.1:Not a defect:Justified> Too many macro definitions code are generated by Configuration tools ,such as:Vector Geny. */
/*******************************************************************************
|  File Name:  Appl_CPID_Callback.c
|  Description:  Implementation of the Dem_DTC_Detection Management
|-------------------------------------------------------------------------------
| (c) This software is the proprietary of Wenzhou Changjiang AutoMobile (CAEA).
|     All rights are reserved by CAEA.
|-------------------------------------------------------------------------------
| Initials      Name                   Company
| --------      --------------------   -----------------------------------------
|
|-------------------------------------------------------------------------------
|               R E V I S I O N   H I S T O R Y
|-------------------------------------------------------------------------------
| Date        Version   Author  Description
| ----------  --------  ------  ------------------------------------------------
| 2016-12-10  V1.0      YJ      first implementation

|******************************************************************************/

/*******************************************************************************
|    Other Header File Inclusion
|******************************************************************************/
#include "CAEA_Types.h"
#include "Std_Types.h"
#include "desc.h"
#include "Appl_CPID_Callback.h"
#include "CPID_Callback.h"
#include "Fridge_Application_Config.h"
#include "Fridge_Basic_Control.h"
#include "HwIO.h"
/*******************************************************************************
|    Macro Definition
|******************************************************************************/

/*******************************************************************************
|    Enum Definition
|******************************************************************************/

/*******************************************************************************
|    Typedef Definition
|******************************************************************************/

/*******************************************************************************
|    Global variables Declaration
|******************************************************************************/

/*******************************************************************************
|    Static local variables Declaration
|******************************************************************************/

/*******************************************************************************
|    static Local Functions Declaration
|******************************************************************************/

/*******************************************************************************
|    Function Source Code
|******************************************************************************/
uint8 CPID_0xF1F1ShortTermAdj(const uint8 * LpCPID_u_DataPtr )
{
	static uint16 CoolCnt = 0;
    uint16 Motor_SpeedDiagValue = (uint16) ((LpCPID_u_DataPtr[1] << 8) | LpCPID_u_DataPtr[2]);

    while(CoolCnt<300)
    {
        CoolCnt++;
        HwIO_COMP_12V_EN_ON();
        HwIO_MCU_PD_SLPn_Enable();
    }

    CoolCnt = 0;

    if(1u == LpCPID_u_DataPtr[0])   
    {
		if(Motor_SpeedDiagValue>4000u)
		{
			Motor_SpeedDiagValue = 4000u;
		}
        FridgeApp_OutputControl(OutputControlObj_Compressor,ControlType_DiagRequest,Motor_SpeedDiagValue);
    }
    else
    {
        FridgeApp_OutputControl(OutputControlObj_Compressor,ControlType_DiagRelease,0);
    }

    return (uint8)E_OK; 
}

uint8 CPID_0xF1F2ShortTermAdj(const uint8 * LpCPID_u_DataPtr )
{

	//照明灯1（制冷）

		if(1u == LpCPID_u_DataPtr[0])   
		{
			if(LpCPID_u_DataPtr[1] > 100u)
			{
				FridgeApp_OutputControl(OutputControlObj_WLed,ControlType_DiagRequest,100u);
			}
			else
			{
				FridgeApp_OutputControl(OutputControlObj_WLed,ControlType_DiagRequest,LpCPID_u_DataPtr[1]);
			}
		}
		else
		{
			FridgeApp_OutputControl(OutputControlObj_WLed,ControlType_DiagRelease,0);
		}




	//照明灯2（制热）

		if(1u == LpCPID_u_DataPtr[2])   
		{
			if(LpCPID_u_DataPtr[3] > 100u)
			{
				FridgeApp_OutputControl(OutputControlObj_HeatFilm,ControlType_DiagRequest,100u);
			}
			else
			{
				FridgeApp_OutputControl(OutputControlObj_HeatFilm,ControlType_DiagRequest,LpCPID_u_DataPtr[3]);
			}
			
		}
		else
		{
			FridgeApp_OutputControl(OutputControlObj_ALed,ControlType_DiagRelease,0);
		}
		



	//UV灯

		if(1u == LpCPID_u_DataPtr[4])   
		{
			if(LpCPID_u_DataPtr[5] > 100u)
			{
				FridgeApp_OutputControl(OutputControlObj_UvLed,ControlType_DiagRequest,100u);
			}
			else
			{
				FridgeApp_OutputControl(OutputControlObj_UvLed,ControlType_DiagRequest,LpCPID_u_DataPtr[5]);
			}
		}
		else
		{
			FridgeApp_OutputControl(OutputControlObj_UvLed,ControlType_DiagRelease,0);
		}
		
	

	
    return (uint8)E_OK;
}
uint8 CPID_0xF1F3ShortTermAdj(const uint8 * LpCPID_u_DataPtr )
{
	//霍尔传感器

		if(1u == LpCPID_u_DataPtr[0])   
		{
			FridgeApp_InputputControl(InputControlObj_Hall,ControlType_DiagRequest,LpCPID_u_DataPtr[1]);
		}
		else
		{
			FridgeApp_InputputControl(InputControlObj_Hall,ControlType_DiagRelease,0);
		}
	

    return (uint8)E_OK;
}

uint8 CPID_0xF1F4ShortTermAdj(const uint8 * LpCPID_u_DataPtr )
{
	//风扇
	if(1u == LpCPID_u_DataPtr[0])
	{
		if(LpCPID_u_DataPtr[1] > 100u)
		{
			FridgeApp_OutputControl(OutputControlObj_Fan,ControlType_DiagRequest,100u);
		}
		else
		{
			FridgeApp_OutputControl(OutputControlObj_Fan,ControlType_DiagRequest,LpCPID_u_DataPtr[1]);
		}
	}
	else 
	{
		FridgeApp_OutputControl(OutputControlObj_Fan,ControlType_DiagRelease,0);
	}
    return (uint8)E_OK;
}

uint8 CPID_0xF1F5ShortTermAdj(const uint8 * LpCPID_u_DataPtr )
{
	//加热膜控制

	
		if(1u == LpCPID_u_DataPtr[0])    
		{
			if(LpCPID_u_DataPtr[1] > 100u)
			{
				FridgeApp_OutputControl(OutputControlObj_HeatFilm,ControlType_DiagRequest,100u);
			}
			else
			{
				FridgeApp_OutputControl(OutputControlObj_HeatFilm,ControlType_DiagRequest,LpCPID_u_DataPtr[1]);
			}
		}
		else
		{
			FridgeApp_OutputControl(OutputControlObj_HeatFilm,ControlType_DiagRelease,0);
		}
	

	//加热丝控制
		if(1u == LpCPID_u_DataPtr[2])   
		{
			if(LpCPID_u_DataPtr[3] > 100u)
			{
				FridgeApp_OutputControl(OutputControlObj_HeatWire,ControlType_DiagRequest,100u);
			}
			else
			{
				FridgeApp_OutputControl(OutputControlObj_HeatWire,ControlType_DiagRequest,LpCPID_u_DataPtr[3]);
			}
		}
		else
		{
			FridgeApp_OutputControl(OutputControlObj_HeatWire,ControlType_DiagRelease,0);
		}
			
	


    return (uint8)E_OK;
}



