// /* polyspace<MISRA-C3:1.1:Not a defect:Justified> Too many macro definitions code are generated by Configuration tools ,such as:Vector Geny. */
// #include "CanDem_Callback.h"
// #include "CanDem_Cfg.h"
// #include "CanDem.h"
// ///#include "STD_BtrM_Cfg.h"
// ///#include "STD_BtrM.h"
// ///#include "STD_BtrCtr.h"
// #include "CanNM.h"
// #include "CanApp.h"
// #include "CAEA_Types.h"
// //#include "Gateway.h"
// #include "Appl_Il_Callback.h"
// #include "SysM.h"
// #include "CAEA_Types.h"
// //#include "NtcCtrl.h"
// #include "task.h"
// #include "Can_Main.h"
// #include "Appl_Can_Callback.h"
// #include "Rte_Can.h"

// uint8  DTC_0x93A016_FLG ;
// uint8  DTC_0x93A117_FLG ;
// uint8  DTC_0x93A38F_FLG ;




// void SetAllDtcCallBackValue(uint8 value)
// {
//     uint8 LeDEM_u_DtcIndex=CanDEM_u_Zero;
//     for(LeDEM_u_DtcIndex=CanDEM_u_Zero;LeDEM_u_DtcIndex < (uint8)CanDem_u_DtcNumber;LeDEM_u_DtcIndex++)
//     {
//         SeDem_u_BswCallbackDTC[LeDEM_u_DtcIndex]=value;
//     }
// }



// /************************************************************************************/
// /*************************************************************************************/

// uint8 Bsw_Callback_DTC_0X93A0_16(void)
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0x93A016_3000ms;
//     static uint8 DTC_0x93A016_NO_3000ms;

//     if(1 == 1)
//     {
//         DTC_0x93A016_NO_3000ms = 0;
//         DTC_0x93A016_3000ms++;
//         if(DTC_0x93A016_3000ms >= 150)
//         {
            
//             DTC_0x93A016_FLG = 1;
//             LeDEM_u_RetVal = 1;
//             DTC_0x93A016_3000ms = 150;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;
//             DTC_0x93A016_FLG = 0;
//         }
//     }
//     else
//     {
//         DTC_0x93A016_3000ms =0;
//         if(DTC_0x93A016_FLG == 1)
//         {
//             DTC_0x93A016_NO_3000ms++;
//             if(DTC_0x93A016_NO_3000ms >= 150) 
//             {
//                 LeDEM_u_RetVal=0;
//                 DTC_0x93A016_FLG = 0;
//                 DTC_0x93A016_NO_3000ms = 150;
//             }
//             else
//             {
//                 LeDEM_u_RetVal=1;
//             }
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;
//             DTC_0x93A016_FLG = 0;
//         }

//     }

//     return (LeDEM_u_RetVal);

// }


// uint8 Bsw_Callback_DTC_0X93A1_17(void)
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0x93A117_3000ms;
//     static uint8 DTC_0x93A117_NO_3000ms;

//     if(1 == 1)
//     {
//         DTC_0x93A117_NO_3000ms = 0;
//         DTC_0x93A117_3000ms++;
//         if(DTC_0x93A117_3000ms >= 150)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0x93A117_FLG = 1;
//             DTC_0x93A117_3000ms = 150;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;
//             DTC_0x93A117_FLG = 0;
            
//         }
//     }
//     else
//     {
//         DTC_0x93A117_3000ms =0;
//         if(DTC_0x93A117_FLG == 1)
//         {
//             DTC_0x93A117_NO_3000ms++;
//             if(DTC_0x93A117_NO_3000ms >= 150) 
//             {
//                 LeDEM_u_RetVal=0;
//                 DTC_0x93A117_FLG = 0;
//                 DTC_0x93A117_NO_3000ms = 150;
//             }
//             else
//             {
//                 LeDEM_u_RetVal=1;
//             }
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;
//             DTC_0x93A117_FLG = 0;
//         }
//     }

//     return (LeDEM_u_RetVal);

// }



// uint8 Bsw_Callback_DTC_0X93A3_8F(void) 
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0x93A38F_5000ms;
//     static uint8 DTC_0x93A38F_NO_5000ms;
//     sint16 LeTempValue;
//     LeTempValue = 1;
//     if((PowerMode_Flg == 1) && (1U == 1) &&(LeTempValue>=830u)) 
//     {
//         DTC_0x93A38F_NO_5000ms = 0;
//         DTC_0x93A38F_5000ms++;
//         if(DTC_0x93A38F_5000ms >= 200)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0x93A38F_FLG = 1;
//             DTC_0x93A38F_5000ms = 200;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;    
//             DTC_0x93A38F_FLG = 0;
//         }
//     }
//     else
//     {
//         DTC_0x93A38F_5000ms =0;
//         if(DTC_0x93A38F_FLG == 1)
//         {
//             DTC_0x93A38F_NO_5000ms++;
//             if(DTC_0x93A38F_NO_5000ms >= 250) 
//             {
//                 LeDEM_u_RetVal=0;
//                 DTC_0x93A38F_FLG = 0;
//                 DTC_0x93A38F_NO_5000ms = 250;
//             }
//             else
//             {
//                 LeDEM_u_RetVal=1;
//             }
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;
//             DTC_0x93A38F_FLG = 0;
//         }
//     }

//     return (LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0X93A4_8F(void) 
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0x93A48F_5000ms;

//     if((PowerMode_Flg == 1) && (1U == 1) &&(1U == 11))
//     {
//         DTC_0x93A48F_5000ms++;
//         if(DTC_0x93A48F_5000ms >= 250)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0x93A48F_5000ms = 250;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0x93A48F_5000ms =0;
//     }

//     return (LeDEM_u_RetVal);


// }
// uint8 Bsw_Callback_DTC_0X93A5_8F(void)  
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0x93A58F_5000ms;

//     if((PowerMode_Flg == 1) && (1U == 11) &&(1U == 1))
//     {
//         DTC_0x93A58F_5000ms++;
//         if(DTC_0x93A58F_5000ms >= 250)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0x93A58F_5000ms = 250;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0x93A58F_5000ms =0;
//     }

//     return (LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0X93A6_8F(void)
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0x93A68F_5000ms;
    

//     if((PowerMode_Flg == 1) && (1U == 1) &&(1U == 1))
//     {
//         DTC_0x93A68F_5000ms++;
//         if(DTC_0x93A68F_5000ms >= 250)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0x93A68F_5000ms = 250;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0x93A68F_5000ms =0;
//     }
    
//     return (LeDEM_u_RetVal);

// }

// ////////////////////////////////////////


// uint8 Bsw_Callback_DTC_0XC046_88(void) 
// {
//     uint8 LeDEM_u_RetVal = 0u;
    
//     if((PowerMode_Flg == 1) && (1U == 11) &&(11== 1))
//     {
//         LeDEM_u_RetVal = 1; 
//     }
//     else
//     {
//         LeDEM_u_RetVal = 0;
//     }
 
//     return ( LeDEM_u_RetVal );
// }
// uint8 Bsw_Callback_DTC_0XC146_87(void)   
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0xC14687_1000ms;
    

//     if((DTC_Enable_Conditions_Flg == 1)&&(1 ==1))  /*2B0*/
//     {
//         DTC_0xC14687_1000ms++;
//         if(DTC_0xC14687_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xC14687_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xC14687_1000ms =0;
//     }

//     return (LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0XD140_87(void)   
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     uint8 MsgTimeout_0x230 = 0u;
//     uint8 MsgTimeout_0x232 = 0u;
//     uint8 MsgTimeout_0x234 = 0u;
//     uint8 MsgTimeout_0x236 = 0u;
//     uint8 MsgTimeout_0x23B = 0u;
//     static uint8 DTC_0xD14087_1000ms;


    
    
//     if((DTC_Enable_Conditions_Flg == 1) && (1 == (MsgTimeout_0x230 || MsgTimeout_0x232 || MsgTimeout_0x234 || MsgTimeout_0x236 || MsgTimeout_0x23B)))
//     {
//         DTC_0xD14087_1000ms++;
//         if(DTC_0xD14087_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xD14087_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xD14087_1000ms =0;
//     }

//     return ( LeDEM_u_RetVal);


// }
// uint8 Bsw_Callback_DTC_0XD246_87(void) 
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     uint8 MsgTimeout_0x246 = 0u;
//     uint8 MsgTimeout_0x247 = 0u;

//     static uint8 DTC_0xD24687_1000ms;
    
    


    
//     if((DTC_Enable_Conditions_Flg == 1)&&(1 == (MsgTimeout_0x247 || MsgTimeout_0x246))) 
//     {
//         DTC_0xD24687_1000ms++;
//         if(DTC_0xD24687_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xD24687_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xD24687_1000ms =0;
//     }

//     return ( LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0XD2A3_87(void) 
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0xD2A387_1000ms;
    

//     if((DTC_Enable_Conditions_Flg == 1)&&(1==1))  /*24C*/
//     {
//         DTC_0xD2A387_1000ms++;
//         if(DTC_0xD2A387_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xD2A387_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xD2A387_1000ms =0;
//     }

//     return ( LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0XC201_87(void)  
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0xC20187_1000ms;
    

//     if((DTC_Enable_Conditions_Flg == 1)&&(1==1))  /*24E*/
//     {
//         DTC_0xC20187_1000ms++;
//         if(DTC_0xC20187_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xC20187_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xC20187_1000ms =0;
//     }

//     return ( LeDEM_u_RetVal);
// }
// uint8 Bsw_Callback_DTC_0XC202_87(void) 
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0xC20287_1000ms;
    

//     if((DTC_Enable_Conditions_Flg == 1)&&(1==1))  /*24F*/
//     {
//         DTC_0xC20287_1000ms++;
//         if(DTC_0xC20287_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xC20287_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xC20287_1000ms =0;
//     }

//     return ( LeDEM_u_RetVal);


// }
// uint8 Bsw_Callback_DTC_0XD2AB_87(void)  
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0xD2AB87_1000ms;
    

//     if((DTC_Enable_Conditions_Flg == 1)&&(1 ==1))   /*2E8*/
//     {
//         DTC_0xD2AB87_1000ms++;
//         if(DTC_0xD2AB87_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xD2AB87_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xD2AB87_1000ms =0;
//     }

//     return ( LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0XD211_87(void)  
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0xD21187_1000ms;
    

//     if((DTC_Enable_Conditions_Flg == 1)&&(1==1))  /*245*/
//     {
//         DTC_0xD21187_1000ms++;
//         if(DTC_0xD21187_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xD21187_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xD21187_1000ms =0;
//     }

//     return ( LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0XD2D8_87(void)  
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     uint8 MsgTimeout_0x2E7 = 0u;
//     uint8 MsgTimeout_0x2E8 = 0u;
//     static uint8 DTC_0xD2D887_1000ms;
    

//     if((DTC_Enable_Conditions_Flg == 1)&&((MsgTimeout_0x2E7 || MsgTimeout_0x2E8) ==1))  /*2E7  2E8*/
//     {
//         DTC_0xD2D887_1000ms++;
//         if(DTC_0xD2D887_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xD2D887_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xD2D887_1000ms =0;
//     }
//     return ( LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0XC164_87(void)  
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     uint8 MsgTimeout_0x228 = 0u;
//     uint8 MsgTimeout_0x22B = 0u;
//     static uint8 DTC_0xC16487_1000ms;
    


//     if((DTC_Enable_Conditions_Flg == 1)&&((MsgTimeout_0x228 || MsgTimeout_0x22B) ==1))  /*228  22B*/
//     {
//         DTC_0xC16487_1000ms++;
//         if(DTC_0xC16487_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xC16487_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xC16487_1000ms =0;
//     }

//     return ( LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0XD164_87(void)  
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0xD16487_1000ms;
    

//     if((DTC_Enable_Conditions_Flg == 1)&&(1==1))  /*2B0*/
//     {
//         DTC_0xD16487_1000ms++;
//         if(DTC_0xD16487_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xD16487_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xD16487_1000ms =0;
//     }

//     return ( LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0XD121_87(void)   
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0xD12187_500ms;
    

//     if((DTC_Enable_Conditions_Flg == 1)&&(1==1))   /*C0*/
//     {
//         DTC_0xD12187_500ms++;
//         if(DTC_0xD12187_500ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xD12187_500ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xD12187_500ms =0;
//     }

//     return ( LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0XC14F_87(void)  
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     uint8 MsgTimeout_0x288 = 0u;
//     uint8 MsgTimeout_0x291 = 0u;
//     static uint8 DTC_0xC14F87_1000ms;
    

    
//     if((DTC_Enable_Conditions_Flg == 1)&&((MsgTimeout_0x288 || MsgTimeout_0x291) ==1))  /*288   291*/
//     {
//         DTC_0xC14F87_1000ms++;
//         if(DTC_0xC14F87_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xC14F87_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xC14F87_1000ms =0;
//     }


//     return ( LeDEM_u_RetVal);

// }
// uint8 Bsw_Callback_DTC_0XD155_87(void)   
// {
//     uint8 LeDEM_u_RetVal = 0u;
//     static uint8 DTC_0xD15587_1000ms;
    

//     if((DTC_Enable_Conditions_Flg == 1)&&(1==1))    /*290*/
//     {
//         DTC_0xD15587_1000ms++;
//         if(DTC_0xD15587_1000ms >= 30)
//         {
//             LeDEM_u_RetVal = 1;
//             DTC_0xD15587_1000ms = 30;
//         }
//         else
//         {
//             LeDEM_u_RetVal=0;            
//         }
//     }
//     else
//     {
//         LeDEM_u_RetVal=0;
//         DTC_0xD15587_1000ms =0;
//     }

//     return ( LeDEM_u_RetVal);

// }







// /******************************************************************************************/
// /*****************************************************************************************/


// uint8 CanDem_GetIgnStatus(void)
// {
//     uint8 LeDEM_u_DtcIndex=CanDEM_u_Zero;

//     return  LeDEM_u_DtcIndex;
// }

// uint8 CanDem_GetBatteryMode(void)/*9-16V*/
// {
//   /*  uint16 e_u_ADValue;
//     static uint8 SysBatteryMode = CanDem_MODE_B;
//     e_u_ADValue = ADCM_GetValidValue(ADCMCFG_BATTERY_CH);
    
//     if(SysBatteryMode == CanDem_MODE_B) 
//     {
//         if( (e_u_ADValue <= (uint16)CAN_DEM_BATTERYH_ON) \
//                 && (e_u_ADValue >= (uint16)CAN_DEM_BATTERYL_ON))    
//         {
//             SysBatteryMode = CanDem_MODE_A;
//         }
//     }
//     else
//     {
//         if( (e_u_ADValue <= (uint16)CAN_DEM_BATTERYL_OFF) \
//                 || (e_u_ADValue >= (uint16)CAN_DEM_BATTERYH_OFF))
//         {
//             SysBatteryMode = CanDem_MODE_B;
//         }
//     }
    
//     return SysBatteryMode;*/
    
//     return 1;

// }



// uint8 CanDem_GetDTC_85EN(void)
// {
//     uint8 e_u_Temp;
//     e_u_Temp = CanDem_GetDTCSetting();
//     return e_u_Temp;
// }

// uint8 CanDem_GetNFirstPowerOn(void)
// {
//   /*  uint8 e_u_Temp;
//     e_u_Temp = CanMain_GetDTCENFlag();*/
    
//     return TRUE;
// }

// uint8 CanDem_GetPowerOn(void)
// {
 
//     return TRUE;
// }

