/* polyspace<MISRA-C3:1.1:Not a defect:Justified> Too many macro definitions code are generated by Configuration tools ,such as:Vector Geny. */
/*******************************************************************************
|  File Name:  Appl_CPID_Callback.c
|  Description:  Implementation of the Dem_DTC_Detection Management
|-------------------------------------------------------------------------------
| (c) This software is the proprietary of Wenzhou Changjiang AutoMobile (CAEA).
|     All rights are reserved by CAEA.
|-------------------------------------------------------------------------------
| Initials      Name                   Company
| --------      --------------------   -----------------------------------------
|
|-------------------------------------------------------------------------------
|               R E V I S I O N   H I S T O R Y
|-------------------------------------------------------------------------------
| Date        Version   Author  Description
| ----------  --------  ------  ------------------------------------------------
| 2016-12-10  V1.0      YJ      first implementation

|******************************************************************************/

/*******************************************************************************
|    Other Header File Inclusion
|******************************************************************************/
#include <NET/Manual/CanDcm/Appl_CPID_Callback.h>
#include "Std_Types.h"
#include "desc.h"
//#include "CPID_Callback.h"
/*******************************************************************************
|    Macro Definition
|******************************************************************************/

/*******************************************************************************
|    Enum Definition
|******************************************************************************/

/*******************************************************************************
|    Typedef Definition
|******************************************************************************/

/*******************************************************************************
|    Global variables Declaration
|******************************************************************************/

/*******************************************************************************
|    Static local variables Declaration
|******************************************************************************/

/*******************************************************************************
|    static Local Functions Declaration
|******************************************************************************/

/*******************************************************************************
|    Function Source Code
|******************************************************************************/


uint8 CPID_CAEAReturnCtlToECU(void)
{
//	CPID_7881RetCtlToECU(0x01);
//	IndApp_CAEARTEtoEcu();
//	Version_Cpid_u_DiagVerFlagCbk(0x00u); /*zgz 200428:确认配置信息*/
    return (uint8)E_OK;
}

uint8 CPID_CAEAShortTermAdj(const uint8 *IOCtrl_Data)
{
	//SeCPID_u_DisableAllSystemOutputs = 0u;
//	Version_Cpid_u_DiagVerFlagCbk(0x55u); /*zgz 200428:确认配置信息*/
	return (uint8)E_OK;
}
/*******************************************************************************
Name              : CPID_7882RetCtlToECU
Syntax            : uint8 CPID_7882RetCtlToECU(void)
Sync/Async        : Synchronous
Reentrancy        : None
Parameters(in)    : None
Parameters(out)   : None
Return value      : (uint8)E_OK
Description       :
Call By           : Appl_Dcm.c
History
<No.>    <author>    <time>    <description>
1
|******************************************************************************/
uint8 CPID_0x7882RetCtlToECU(const uint8 * LpCPID_u_DataPtr )
{
    uint8 LeCPID_u_Ret = kDescNrcNone;
    if(LpCPID_u_DataPtr != NULL_PTR)
    {
 //       LeCPID_u_Ret = CPID_7882RetCtlToECU();
    }
    return LeCPID_u_Ret;
}
/*******************************************************************************
Name              : CPID_7882ShortTermAdj
Syntax            : uint8 CPID_7882ShortTermAdj(void)
Sync/Async        : Synchronous
Reentrancy        : None
Parameters(in)    : None
Parameters(out)   : None
Return value      : (uint8)E_OK
Description       :
Call By           : Appl_Dcm.c
History
<No.>    <author>    <time>    <description>
1
|******************************************************************************/
uint8 CPID_0x7882ShortTermAdj(const uint8 * LpCPID_u_DataPtr )
{
    uint8 LeCPID_u_Ret = kDescNrcNone;
    if(LpCPID_u_DataPtr != NULL_PTR)
    {
//        LeCPID_u_Ret = CPID_7882ShortTermAdj(LpCPID_u_DataPtr);
    }
    return LeCPID_u_Ret;
}

/*******************************************************************************
Name              : CPID_7882RetCtlToECU
Syntax            : uint8 CPID_7882RetCtlToECU(void)
Sync/Async        : Synchronous
Reentrancy        : None
Parameters(in)    : None
Parameters(out)   : None
Return value      : (uint8)E_OK
Description       :
Call By           : Appl_Dcm.c
History
<No.>    <author>    <time>    <description>
1
|******************************************************************************/
uint8 CPID_0x2001RetCtlToECU(const uint8 * LpCPID_u_DataPtr )
{
    uint8 LeCPID_u_Ret = kDescNrcNone;
    if(LpCPID_u_DataPtr != NULL_PTR)
    {
//        LeCPID_u_Ret = CPID_2001RetCtlToECU();
    }
    return LeCPID_u_Ret;
}
/*******************************************************************************
Name              : CPID_7882ShortTermAdj
Syntax            : uint8 CPID_7882ShortTermAdj(void)
Sync/Async        : Synchronous
Reentrancy        : None
Parameters(in)    : None
Parameters(out)   : None
Return value      : (uint8)E_OK
Description       :
Call By           : Appl_Dcm.c
History
<No.>    <author>    <time>    <description>
1
|******************************************************************************/
uint8 CPID_0x2001ShortTermAdj(const uint8 * LpCPID_u_DataPtr )
{
    uint8 LeCPID_u_Ret = kDescNrcNone;
    if(LpCPID_u_DataPtr != NULL_PTR)
    {
 //       LeCPID_u_Ret = CPID_2001ShortTermAdj(LpCPID_u_DataPtr);
    }
    return LeCPID_u_Ret;
}

/*******************************************************************************
Name              : CPID_7882RetCtlToECU
Syntax            : uint8 CPID_7882RetCtlToECU(void)
Sync/Async        : Synchronous
Reentrancy        : None
Parameters(in)    : None
Parameters(out)   : None
Return value      : (uint8)E_OK
Description       :
Call By           : Appl_Dcm.c
History
<No.>    <author>    <time>    <description>
1
|******************************************************************************/
uint8 CPID_0x2002RetCtlToECU(const uint8 * LpCPID_u_DataPtr )
{
    uint8 LeCPID_u_Ret = kDescNrcNone;
    if(LpCPID_u_DataPtr != NULL_PTR)
    {
  //      LeCPID_u_Ret = CPID_2002RetCtlToECU();
    }
    return LeCPID_u_Ret;
}
/*******************************************************************************
Name              : CPID_7882ShortTermAdj
Syntax            : uint8 CPID_7882ShortTermAdj(void)
Sync/Async        : Synchronous
Reentrancy        : None
Parameters(in)    : None
Parameters(out)   : None
Return value      : (uint8)E_OK
Description       :
Call By           : Appl_Dcm.c
History
<No.>    <author>    <time>    <description>
1
|******************************************************************************/
uint8 CPID_0x2002ShortTermAdj(const uint8 * LpCPID_u_DataPtr )
{
    uint8 LeCPID_u_Ret = kDescNrcNone;
    if(LpCPID_u_DataPtr != NULL_PTR)
    {
 //       LeCPID_u_Ret = CPID_2002ShortTermAdj(LpCPID_u_DataPtr);
    }
    return LeCPID_u_Ret;
}
/*******************************************************************************
Name              : CPID_7882RetCtlToECU
Syntax            : uint8 CPID_7882RetCtlToECU(void)
Sync/Async        : Synchronous
Reentrancy        : None
Parameters(in)    : None
Parameters(out)   : None
Return value      : (uint8)E_OK
Description       :
Call By           : Appl_Dcm.c
History
<No.>    <author>    <time>    <description>
1
|******************************************************************************/
uint8 CPID_0x2003RetCtlToECU(const uint8 * LpCPID_u_DataPtr )
{
    uint8 LeCPID_u_Ret = kDescNrcNone;
    if(LpCPID_u_DataPtr != NULL_PTR)
    {
 //       LeCPID_u_Ret = CPID_2003RetCtlToECU();
    }
    return LeCPID_u_Ret;
}
/*******************************************************************************
Name              : CPID_7882ShortTermAdj
Syntax            : uint8 CPID_7882ShortTermAdj(void)
Sync/Async        : Synchronous
Reentrancy        : None
Parameters(in)    : None
Parameters(out)   : None
Return value      : (uint8)E_OK
Description       :
Call By           : Appl_Dcm.c
History
<No.>    <author>    <time>    <description>
1
|******************************************************************************/
uint8 CPID_0x2003ShortTermAdj(const uint8 * LpCPID_u_DataPtr )
{
    uint8 LeCPID_u_Ret = kDescNrcNone;
    if(LpCPID_u_DataPtr != NULL_PTR)
    {
//        LeCPID_u_Ret = CPID_2003ShortTermAdj(LpCPID_u_DataPtr);
    }
    return LeCPID_u_Ret;
}
/*******************************************************************************
Name              : CPID_7882RetCtlToECU
Syntax            : uint8 CPID_7882RetCtlToECU(void)
Sync/Async        : Synchronous
Reentrancy        : None
Parameters(in)    : None
Parameters(out)   : None
Return value      : (uint8)E_OK
Description       :
Call By           : Appl_Dcm.c
History
<No.>    <author>    <time>    <description>
1
|******************************************************************************/
uint8 CPID_0x2004RetCtlToECU(const uint8 * LpCPID_u_DataPtr )
{
    uint8 LeCPID_u_Ret = kDescNrcNone;
    if(LpCPID_u_DataPtr != NULL_PTR)
    {
  //      LeCPID_u_Ret = CPID_2004RetCtlToECU();
    }
    return LeCPID_u_Ret;
}
/*******************************************************************************
Name              : CPID_7882ShortTermAdj
Syntax            : uint8 CPID_7882ShortTermAdj(void)
Sync/Async        : Synchronous
Reentrancy        : None
Parameters(in)    : None
Parameters(out)   : None
Return value      : (uint8)E_OK
Description       :
Call By           : Appl_Dcm.c
History
<No.>    <author>    <time>    <description>
1
|******************************************************************************/
uint8 CPID_0x2004ShortTermAdj(const uint8 * LpCPID_u_DataPtr )
{
    uint8 LeCPID_u_Ret = kDescNrcNone;
    if(LpCPID_u_DataPtr != NULL_PTR)
    {
//        LeCPID_u_Ret = CPID_2004ShortTermAdj(LpCPID_u_DataPtr);
    }
    return LeCPID_u_Ret;
}
