#ifndef _FDB_APP_H_
#define _FDB_APP_H_

#include <stdint.h>
#include <stddef.h>

#include "fdb_def.h"

#define FDB_KEY_BT_LINKKEY          0x00010000 //!< bt link key storage index
#define FDB_KEY_CONTROLLER_INFO     0x00010001 //!< controller information storage index
#define FDB_KEY_RANDOM_SEED         0x00010002 //!< save random seed generated by TRNG during first boot up
#define FDB_KEY_MESH_INFO           0x00010003 //!< mesh informations which change frequency is low
#define FDB_KEY_MESH_INFO_VOLATILE  0x00010004 //!< mesh informations which change frequency is high
#define FDB_KEY_BTDM_LIB_BASE       0x00020000 //!< base index used to store host data
#define FDB_KEY_USER_BASE           0x00030000 // !< base index used to store user data

/* 
 * Notes: Define a few ID used to store uds data.
 * Format: Two bytes. High byte is data length, and low byte is ID.
 *
 * Author: chuzewei on 2026/03/02
 */
enum{
    FDB_KEY_USER_1 = 0x00030001,
    FDB_KEY_USER_2 = 0x00030002,
    FDB_KEY_USER_3 = 0x00030003,
    FDB_KEY_USER_4 = 0x00030004,
    FDB_KEY_USER_5 = 0x00030005,
    FDB_KEY_USER_6 = 0x00030006,
    FDB_KEY_USER_7 = 0x00030007,
    FDB_KEY_USER_8 = 0x00030008,
    FDB_KEY_USER_9 = 0x00030009,
    FDB_KEY_USER_10 = 0x0003000a,
    FDB_KEY_USER_11 = 0x0003000b,
    FDB_KEY_USER_12 = 0x0003000c,
    FDB_KEY_USER_13 = 0x0003000d,
    FDB_KEY_USER_14 = 0x0003000e,
    FDB_KEY_USER_15 = 0x0003000f,
};

/* DTC */
#define USER_ID_UDS_U300616                 (0x1601)
#define USER_ID_UDS_U300617                 (0x1602)
#define USER_ID_UDS_U007300                 (0x1603)
#define USER_ID_UDS_B13E153                 (0x1604)

/* error code */
#define USER_ID_UDS_ERR_COUNT               (0x0A05)

/* Data Identifier */
#define USER_ID_UDS_F101                    (0x0806)
#define USER_ID_UDS_F112                    (0x0807)
#define USER_ID_UDS_D135                    (0x1008)
#define USER_ID_UDS_F110                    (0x1009)
#define USER_ID_UDS_F190                    (0x110A)
#define USER_ID_UDS_F197                    (0x080B)
#define USER_ID_UDS_F198                    (0x100C)
#define USER_ID_UDS_F199                    (0x040D)
#define USER_ID_UDS_F1A2                    (0x040E)

/* reserved for expanding in future */
#define USER_ID_UDS_RESERVED                (0x690F)

/* Get fdb key from user data id */
#define FDBKEY_FROM_USERID(a)               (((a) & 0x00FF) | FDB_KEY_USER_BASE)

/* Get user data length from id */
#define USERID_DATA_LEN(a)                  (((a) >> 8) & 0xFF)

/* define an id table from which find out it according to a key */
#define USER_ID_UDS_TABLE                   {\
USER_ID_UDS_U300616,\
USER_ID_UDS_U300617,\
USER_ID_UDS_U007300,\
USER_ID_UDS_B13E153,\
USER_ID_UDS_ERR_COUNT,\
USER_ID_UDS_F101,\
USER_ID_UDS_F112,\
USER_ID_UDS_D135,\
USER_ID_UDS_F110,\
USER_ID_UDS_F190,\
USER_ID_UDS_F197,\
USER_ID_UDS_F198,\
USER_ID_UDS_F199,\
USER_ID_UDS_F1A2\
}

/* Get user data id from fdb key */
extern uint16_t get_userid_from_fdbkey(uint32_t key);
extern uint8_t uds_flash_set(uint16_t id, uint8_t *value, uint32_t length);
extern uint8_t uds_flash_get(uint16_t id, uint8_t *value, uint32_t length);
extern uint8_t uds_flash_del(uint16_t id);
extern void uds_ext_flash_test(void);
extern void uds_flash_test_read(void);
extern void uds_flash_test_write(void);
extern void uds_flash_test_del(uint16_t id);
extern void uds_flash_test_add(uint16_t id);
extern void uds_flash_test_lookup(uint16_t id);

/* Above for N72 BT module */

int flashdb_init(void);

fdb_err_t flashdb_set(uint32_t key, uint8_t *value, uint32_t length);

size_t flashdb_get(uint32_t key, uint8_t *value, uint32_t length);

size_t flashdb_get_length(uint32_t key);

fdb_err_t flashdb_del(uint32_t key);

/* 
 * These following 4 functions are used to read / write /erase the extenal
 * flash IS25LP040E.
 */
fdb_err_t flashdb_exter_set(uint32_t key, uint8_t *value, uint32_t length);
size_t flashdb_exter_get(uint32_t key, uint8_t *value, uint32_t length);
size_t flashdb_exter_get_length(uint32_t key);
fdb_err_t flashdb_exter_del(uint32_t key);

#endif
