/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'Project' 
 * Target:  'Project' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM33_DSP_FP.h"

/* Keil::Compiler&ARM Compiler:I/O:STDERR&Breakpoint@1.2.0 */
#define RTE_Compiler_IO_STDERR          /* Compiler I/O: STDERR */
#define RTE_Compiler_IO_STDERR_BKPT     /* Compiler I/O: STDERR Breakpoint */


#endif /* RTE_COMPONENTS_H */
